version: 17
jobs:
- name: build
  jobExecutor: blog
  steps:
  - !CommandStep
    name: build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - export HOME=/home/ubuntu
      - cd /home/ubuntu/app/blog && sh ./depoly.sh
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: no_idea/blog
    remoteUrl: https://github.com/NoCreativeAndNoIdea/blog
    userName: muziyan
    passwordSecret: access-token
    withLfs: true
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
    paths: '**'
    projects: blog
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
